export class Banca{
    id                                  : number;
    ativo                               : boolean;
    nome                                : string;
    descricao                           : string;
    telefone                            : string;
    email_alerta                        : string;
    valor_min_cupom                     : number;
    valor_max_cupom                     : number;
    premio_max_cupom                    : number;
    cotacao_max_cupom                   : number;
    alerta_cupom_simples_cotacao_acima  : number;
    alerta_cupom_multiplo_cotacao_acima : number;
    proprietario                        : string;
    email_proprietario                  : string;
    mensagemFinalBilhete                : string;
    telefone_proprietario               : string;
    minimoPartidaBilhete                : string;
    limitePartidaUnicaBilhete           : number;
    recadastrarPartidas                 : Boolean = false;
    recadastrarOpcaoCotacao             : Boolean = false;
    desativarCampeonatosVazios          : Boolean = false;
    enviarEmailMarketing                : Boolean = false;
    porcentagemOdds                     : number  = 0;
    limiteCotacao                       : number  = 0;
    contaBancaUm                        : String;
    contaBancaDois                      : String;
    atualizandoPartidas                 : Boolean;
    tempoLimiteCancelamentoBilhete      : number  = 0;
    zerarCaixaAoFechar                  : Boolean;
    rankingPersonalizado                : boolean;
    suspenderAoVivo                     : boolean;
    diaDaSemanaFecharCaixa              : any;
    pagamentoBilheteAutomatico          : boolean;
    focoFutebol                         : boolean;
    focoBolao                           : boolean;
    focoBinario                         : boolean;
    vizualizarParametrosModalidade      : boolean;
    valorPadraoBilheteAcumuladaoBolao   : number = 0;
    descricaoBinario                    : string;
    baixarPorLinkComum                  : boolean;
    linkDownload                        : string;
    linkDownloadAlternativo             : string;
    acumuladao1x2                       : boolean;
}
